### ISSUE TITLE
Error with dotted keys

### ISSUE THREAD

**Issue by salim-b** [gnprice/toml-cli#2]
toml-cli has obvious issues with [dotted keys](https://github.com/toml-lang/toml#keys).

The following TOML snippet

```toml
la.la = "bla"
```

throws the error

```
Error: TomlError { message: "TOML parse error at line 1, column 3\n  |\n1 | la.la = \"bla\"\n  |   ^\nUnexpected `.`\nExpected `=`\n" }
```

(or more readable:)

```
TOML parse error at line 1, column 3
  |
1 | la.la = "bla"
  |   ^
Unexpected `.`
Expected `=`
```

The same key in table notation on the other hand is parsed fine:

```toml
[la]
la = "bla"
```

Would be awesome if this could be fixed! 🙃

**Comment by gnprice** [comment]
Thanks @salim-b for the report!

It looks like this was fixed by 8f93d2f46, which upgraded the `toml_edit` dependency. That fix was released in `toml-cli` v0.2.1.
