### ISSUE TITLE
Linux binaries

### ISSUE THREAD

**Issue by teknopaul** [gnprice/toml-cli#3]
Hi are Ubuntu binaries published anywhere?

Any objection if I publish a .deb from download.tp23.org?

**Comment by szymonrychu** [comment]
or just a binary?
it would be quite useful util (like `jq` or `yq`), but without binaries this development effort seems to be mostly wasted (because I don't want to install whole rust language and compiler to get the `toml` editor out of it).

**Comment by ffMathy** [comment]
I agree with the above. Having a proper release exposing a download link would be nice.

**Comment by gnprice** [comment]
Good news! I've now published Linux binaries for the latest release (and a couple of older ones.) Find them here: https://github.com/gnprice/toml-cli/releases

These binaries will work on Ubuntu as well as any other Linux distribution. They're statically linked, which means they don't depend on any external libraries supplied by the OS.

The current binaries are for the x86_64 architecture only, which covers a large majority of desktops, laptops, and servers. For ARM, see #21.
