### ISSUE TITLE
Some instructions in README.md about installation

### ISSUE THREAD

**Issue by prasannjeet** [gnprice/toml-cli#9]
Hey! This might seem very trivial, but for someone very new to this, it would be great if you provide some instructions on how to install the cli? would be great! Thanks.

**Comment by ghost** [comment]
Yes, how does one install this in ubuntu and MacOs?

**Comment by gnprice** [comment]
Good question! Thanks both.

I've just pushed fc21dee4a which adds to the README an answer to this question. For completeness, here's that answer:

---

If you have Cargo (the Rust build tool) installed, you can install the `toml` CLI by running:
```
$ cargo install toml-cli
```

To install Cargo, follow the instructions [on rust-lang.org][install-rust].

Currently no binaries are published for releases.  Publishing binaries, in various convenient forms, is a desired future step ([#3], [#5]).

[install-rust]: https://www.rust-lang.org/learn/get-started
[#3]: https://github.com/gnprice/toml-cli/issues/3
[#5]: https://github.com/gnprice/toml-cli/issues/5

---

So the answer isn't quite as convenient for many people as it would ideally be, but that's the answer as things stand. I would like to make it more convenient, too, which we can track in those other issues.

**Comment by gnprice** [comment]
(And by the way, for anyone who doesn't have Rust/Cargo installed, I'd encourage you to [try it out](https://www.rust-lang.org/learn/get-started) — it may be simpler to install than you think! The Rust folks have really done quite a lot to make installing it an easy process. But I understand that in many situations it is a barrier, and that some nice isolated binary releases would be quite useful too.)

**Comment by gnprice** [comment]
Update: I've now published Linux binaries for the latest release (and a few others.) Find them here:
  https://github.com/gnprice/toml-cli/releases
Also updated the README accordingly: 931b6694ba0cc2d081b2a72cb648a8b69dc56f02.

Binaries for macOS are still an open task, #22.
